"""Regenerate PLAN.md and the README diagrams section.

Sources of truth:
  maine-redemption-plan.html   the plan's text and tables
  diagrams/NN-*.md             one Mermaid chart each (### title, caption, ```mermaid block)

Outputs:
  PLAN.md                      the plan as Markdown, with the charts placed in their sections
  README.md                    the block between the DIAGRAMS markers

Run:  python scripts/build_docs.py          (rewrite files)
      python scripts/build_docs.py --check  (exit 1 if anything is out of date)
"""
import pathlib
import re
import sys
from html.parser import HTMLParser

ROOT = pathlib.Path(__file__).resolve().parent.parent
REPO = "https://github.com/wbp318/bottle_recycling_2027"
PLAN_HTML = ROOT / "maine-redemption-plan.html"
PLAN_MD = ROOT / "PLAN.md"
README = ROOT / "README.md"
DIAGRAMS = ROOT / "diagrams"
BEGIN, END = "<!-- BEGIN DIAGRAMS (generated by scripts/build_docs.py) -->", "<!-- END DIAGRAMS -->"

# Which charts go after which plan heading (matched on the heading text).
PLACEMENT = {
    "How the cash moves": ["01", "02"],
    "Unit economics at three volumes": ["08"],
    "Working with partners already in Maine": ["05"],
    "3. Where to put it": ["09"],
    "Candidate site: a partner's farm": ["03", "06", "07"],
    "4. First 90 days": ["04", "10", "11", "12"],
}


# ---------- HTML to Markdown ----------

class Node:
    def __init__(self, tag, attrs=None, parent=None):
        self.tag, self.attrs, self.parent, self.children = tag, dict(attrs or {}), parent, []

    @property
    def cls(self):
        return self.attrs.get("class", "").split()


class TreeBuilder(HTMLParser):
    VOID = {"br", "img", "meta", "link", "hr", "input"}

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.root = self.cur = Node("root")

    def handle_starttag(self, tag, attrs):
        node = Node(tag, attrs, self.cur)
        self.cur.children.append(node)
        if tag not in self.VOID:
            self.cur = node

    def handle_endtag(self, tag):
        n = self.cur
        while n is not self.root and n.tag != tag:
            n = n.parent
        if n is not self.root:
            self.cur = n.parent

    def handle_data(self, data):
        self.cur.children.append(data)


def inline(node):
    out = []
    for c in node.children:
        if isinstance(c, str):
            out.append(re.sub(r"\s+", " ", c))
        elif c.tag in ("strong", "b"):
            out.append(f"**{inline(c).strip()}**")
        elif c.tag in ("em", "i"):
            out.append(f"_{inline(c).strip()}_")
        elif c.tag == "a":
            out.append(f"[{inline(c).strip()}]({c.attrs.get('href', '')})")
        elif c.tag == "code":
            out.append(inline(c))
        elif c.tag == "br":
            out.append("<br>")
        else:
            out.append(inline(c))
    return "".join(out)


def table(node):
    rows = []
    for section in node.children:
        if isinstance(section, str):
            continue
        for tr in (section.children if section.tag in ("thead", "tbody", "tfoot") else [section]):
            if isinstance(tr, str) or tr.tag != "tr":
                continue
            cells = [inline(td).strip().replace("|", "\\|") for td in tr.children
                     if not isinstance(td, str) and td.tag in ("td", "th")]
            if section.tag == "tfoot":
                cells = [f"**{c}**" if c else c for c in cells]
            rows.append(cells)
    if not rows:
        return ""
    lines = ["| " + " | ".join(rows[0]) + " |", "| " + " | ".join("---" for _ in rows[0]) + " |"]
    lines += ["| " + " | ".join(r) + " |" for r in rows[1:]]
    return "\n".join(lines)


def blocks(node):
    """Yield (kind, text) for each block-level element, in order."""
    for c in node.children:
        if isinstance(c, str):
            continue
        if c.tag in ("style", "script", "title", "link", "meta"):
            continue
        if c.tag in ("h1", "h2", "h3"):
            yield c.tag, inline(c).strip()
        elif c.tag == "p":
            text = inline(c).strip()
            if "lede" in c.cls:
                yield "p", f"**{text}**"
            elif "small" in c.cls:
                yield "p", f"_{text}_"
            else:
                yield "p", text
        elif c.tag in ("ul", "ol"):
            items = [inline(li).strip() for li in c.children if not isinstance(li, str) and li.tag == "li"]
            mark = (lambda i: f"{i}.") if c.tag == "ol" else (lambda i: "-")
            yield "p", "\n".join(f"{mark(i)} {t}" for i, t in enumerate(items, 1))
        elif c.tag == "div" and "tbl" in c.cls:
            for t in c.children:
                if not isinstance(t, str) and t.tag == "table":
                    yield "p", table(t)
        elif c.tag == "div" and ("eyebrow" in c.cls or "stamp" in c.cls):
            yield "p", f"_{inline(c).strip()}_"
        elif c.tag == "div" and "verdicts" in c.cls:
            for v in c.children:
                if isinstance(v, str):
                    continue
                tag = next((inline(x).strip() for x in v.children if not isinstance(x, str) and x.tag == "span"), "")
                title = next((inline(x).strip() for x in v.children if not isinstance(x, str) and x.tag == "strong"), "")
                body = next((inline(x).strip() for x in v.children if not isinstance(x, str) and x.tag == "p"), "")
                yield "p", f"> **{tag}: {title}.** {body}"
        elif c.tag == "div" and ("callout" in c.cls or "note" in c.cls):
            paras = [inline(p).strip() for p in c.children if not isinstance(p, str) and p.tag == "p"]
            yield "p", "\n>\n".join(f"> {p}" for p in paras)
        else:
            yield from blocks(c)


def diagram(num, level="####"):
    path = next(DIAGRAMS.glob(f"{num}-*.md"))
    text = path.read_text(encoding="utf-8").strip()
    return re.sub(r"^### ", level + " ", text, count=1)


def build_plan():
    tree = TreeBuilder()
    tree.feed(PLAN_HTML.read_text(encoding="utf-8"))
    out, pending = [], []
    for kind, text in blocks(tree.root):
        if kind in ("h1", "h2", "h3"):
            out += pending
            pending = []
            out.append({"h1": "#", "h2": "##", "h3": "###"}[kind] + " " + text)
            if kind == "h1":
                out.append(
                    f"_This file is generated from [maine-redemption-plan.html]({REPO}/blob/main/maine-redemption-plan.html) "
                    f"and the [diagrams folder]({REPO}/tree/main/diagrams) by "
                    f"[scripts/build_docs.py]({REPO}/blob/main/scripts/build_docs.py). "
                    "Edit those; CI regenerates this file on every push to main._")
            pending = [diagram(n) for n in PLACEMENT.get(text, [])]
        else:
            out.append(text)
    out += pending
    header = "<!-- Generated file. Do not edit by hand: edit maine-redemption-plan.html or diagrams/, then run scripts/build_docs.py -->"
    # The eyebrow line comes before the title in the HTML; put the title first.
    if out and out[0].startswith("_") and len(out) > 1 and out[1].startswith("# "):
        out[0], out[1] = out[1], out[0]
    return header + "\n\n" + "\n\n".join(b for b in out if b) + "\n"


def build_readme():
    text = README.read_text(encoding="utf-8")
    charts = sorted(DIAGRAMS.glob("[0-9][0-9]-*.md"))
    body = [BEGIN]
    for i, path in enumerate(charts, 1):
        chart = path.read_text(encoding="utf-8").strip()
        body.append(re.sub(r"^### ", f"### {i}. ", chart, count=1))
    body.append(END)
    pattern = re.compile(re.escape(BEGIN) + ".*?" + re.escape(END), re.S)
    if not pattern.search(text):
        sys.exit("README.md is missing the DIAGRAMS markers")
    return pattern.sub(lambda _: "\n\n".join(body), text)


def main():
    check = "--check" in sys.argv
    stale = []
    for path, content in ((PLAN_MD, build_plan()), (README, build_readme())):
        old = path.read_text(encoding="utf-8") if path.exists() else ""
        if old != content:
            stale.append(path.name)
            if not check:
                path.write_text(content, encoding="utf-8", newline="\n")
    if check and stale:
        print("Out of date: " + ", ".join(stale) + ". Run: python scripts/build_docs.py")
        sys.exit(1)
    print(("Updated: " + ", ".join(stale)) if stale else "Docs are up to date.")


if __name__ == "__main__":
    main()
